const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const UI=require('../app/src/main/assets/ui-runtime.js');
function app(){const calls=[],els={dniConsent:{checked:false}};const native=new Proxy({}, {get:(_,name)=>(...args)=>{calls.push([name,...args]);return name==='consumeNotification'?'{}':true;}});const window={SolucionaNative:native,SolucionaPriority:native,addEventListener:()=>{}};
 const ctx=vm.createContext({window,SolucionaPriority:native,SolucionaUI:UI,Intl,confirm:()=>true,console,document:{querySelector:s=>els[s.slice(1)],getElementById:id=>els[id]}});
 const html=fs.readFileSync(path.resolve(__dirname,'../app/src/main/assets/index.html'),'utf8'),inline=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const state='));
 vm.runInContext(inline.slice(0,inline.indexOf('if(!N||')),ctx);vm.runInContext("render=()=>{};toast=()=>{};state.profile={uid:'client',role:'CLIENT'};state.screen='account';",ctx);
 vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../app/src/main/assets/priority.js'),'utf8'),ctx);
 // In a browser global window properties resolve as global identifiers.
 for(const key of Object.keys(window))if(!(key in ctx))ctx[key]=window[key];
 return {calls,els,run:s=>vm.runInContext(s,ctx)};
}
test('identity is subscribed only while the screen is open',()=>{const a=app();a.run('solOpenIdentity();render();render()');assert.equal(a.calls.filter(c=>c[0]==='subscribeIdentity').length,1);a.run("setScreen('account')");assert.equal(a.calls.filter(c=>c[0]==='stopIdentity').length,1);});
test('DNI consent is required and review text is escaped',()=>{const a=app();a.run("solOpenIdentity();solUploadDni('DNI_FRONT')");assert.equal(a.calls.filter(c=>c[0]==='chooseDni').length,0);a.run("window.solucionaPriorityEvent(true,{kind:'identity',ownerUid:'client',status:'REJECTED',front:true,back:true,reviewNote:'<img onerror=evil()>'})");assert.ok(a.run('views.identity()').includes('&lt;img'));a.els.dniConsent.checked=true;a.run("solUploadDni('DNI_FRONT')");assert.deepEqual(a.calls.find(c=>c[0]==='chooseDni'),['chooseDni','DNI_FRONT',true]);});
test('late responses for other accounts and orders do not replace the current order',()=>{const a=app();a.run("solOpenService('order');window.solucionaPriorityEvent(true,{kind:'service',ownerUid:'client',id:'order',clientUid:'client',description:'actual',status:'REQUESTED'});window.solucionaPriorityEvent(true,{kind:'service',ownerUid:'other',id:'order',description:'wrong'});window.solucionaPriorityEvent(true,{kind:'service',ownerUid:'client',id:'previous',description:'wrong'})");assert.ok(a.run('views.serviceDetails()').includes('actual'));assert.ok(!a.run('views.serviceDetails()').includes('wrong'));a.run("setScreen('account')");assert.ok(a.calls.some(c=>c[0]==='stopService'));});
test('acceptance sends displayed revision and boolean answer',()=>{const a=app();a.run("solOpenService('order');window.solucionaPriorityEvent(true,{kind:'service',ownerUid:'client',id:'order',clientUid:'client',status:'ACCEPTED',budget:{revision:3,status:'PENDING',totalCents:10000}});solBudgetDecision(true)");const sent=JSON.parse(a.calls.find(c=>c[0]==='respondBudget')[1]);assert.deepEqual(sent,{requestId:'order',revision:3,accept:true});});
