const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module'),path=require('node:path');
function setup({verified=true,denied=false,failCommit=false}={}){
 const docs=new Map([['users/user',{fields:{accountStatus:{stringValue:'ACTIVE'}}}]]),objects=new Map(),calls=[];
 const source=fs.readFileSync(path.resolve(__dirname,'../../../worker-r2/src/index.ts'),'utf8').replace("import { createRemoteJWKSet, jwtVerify } from 'jose';",'').replace('export default {','globalThis.worker = {').replace('export interface Env','interface Env');
 const context={Request,Response,Headers,URL,File,FormData,Uint8Array,AbortSignal,crypto,createRemoteJWKSet:()=>({}),jwtVerify:async()=>({payload:{sub:'user',email_verified:verified}}),fetch:async(url,init={})=>{
  const key=String(url).split('/documents/')[1];calls.push({url,init});
  if(String(url).endsWith('documents:commit')){if(failCommit)return Response.json({error:'conflict'},{status:409});for(const write of JSON.parse(init.body).writes){const k=write.update.name.split('/documents/')[1];docs.set(k,{...write.update,updateTime:'new'});}return Response.json({writeResults:[]});}
  if(denied&&key?.includes('/attachments/'))return Response.json({error:'forbidden'},{status:403});
  return docs.has(key)?Response.json(docs.get(key)):Response.json({error:'missing'},{status:404});
 }};
 vm.createContext(context);vm.runInContext(stripTypeScriptTypes(source),context);
 const env={FIREBASE_PROJECT_ID:'test',DOCUMENTS:{put:async(k,data,opt)=>objects.set(k,{data,opt}),delete:async k=>objects.delete(k),get:async k=>{const o=objects.get(k);return o?{body:o.data,httpEtag:'etag',writeHttpMetadata:h=>h.set('content-type',o.opt.httpMetadata.contentType)}:null;}}};
 const send=(pathname,form)=>context.worker.fetch(new Request('https://files.example'+pathname,{method:form?'POST':'GET',headers:{authorization:'Bearer token'},...(form?{body:form}:{})}),env);
 return {docs,objects,calls,send};
}
function imageForm(type,requestId=''){const f=new FormData();f.set('type',type);f.set('requestId',requestId);f.set('consent','true');f.set('file',new File([new Uint8Array([255,216,255,0,0])],'photo.jpg',{type:'image/jpeg'}));return f;}
test('DNI records are saved privately with pending status and consent',async()=>{const h=setup();const res=await h.send('/v1/identity-documents',imageForm('DNI_FRONT'));assert.equal(res.status,201);const doc=h.docs.get('identity_submissions/user');assert.equal(doc.fields.status.stringValue,'PENDING');assert.equal(doc.fields.consentVersion.stringValue,'identity-v1');assert.ok(doc.fields.front.mapValue.fields.storageKey.stringValue.startsWith('identities/user/'));assert.ok(h.calls.some(c=>String(c.url).endsWith('documents:commit')));});
test('unverified accounts cannot upload',async()=>{const h=setup({verified:false});const res=await h.send('/v1/identity-documents',imageForm('DNI_FRONT'));assert.equal(res.status,401);assert.equal(h.objects.size,0);});
test('DNI upload requires explicit consent and real image magic bytes',async()=>{const h=setup(),f=imageForm('DNI_FRONT');f.set('consent','false');assert.equal((await h.send('/v1/identity-documents',f)).status,400);const fake=imageForm('DNI_FRONT');fake.set('file',new File(['not-image'],'x.jpg',{type:'image/jpeg'}));assert.equal((await h.send('/v1/identity-documents',fake)).status,415);assert.equal(h.objects.size,0);});
test('metadata commit failure cleans up new object',async()=>{const h=setup({failCommit:true});assert.equal((await h.send('/v1/identity-documents',imageForm('DNI_BACK'))).status,409);assert.equal(h.objects.size,0);});
test('photos are limited to owner before acceptance',async()=>{const h=setup();h.docs.set('service_requests/order',{fields:{clientUid:{stringValue:'other'},status:{stringValue:'REQUESTED'}}});assert.equal((await h.send('/v1/request-photos',imageForm('REQUEST_PHOTO','order'))).status,403);h.docs.get('service_requests/order').fields.clientUid.stringValue='user';h.docs.get('service_requests/order').fields.status.stringValue='ACCEPTED';assert.equal((await h.send('/v1/request-photos',imageForm('REQUEST_PHOTO','order'))).status,403);});
test('photos commit counter and metadata atomically and enforce count',async()=>{const h=setup();h.docs.set('service_requests/order',{name:'projects/test/databases/(default)/documents/service_requests/order',updateTime:'v1',fields:{clientUid:{stringValue:'user'},status:{stringValue:'REQUESTED'}}});assert.equal((await h.send('/v1/request-photos',imageForm('REQUEST_PHOTO','order'))).status,201);const writes=JSON.parse(h.calls.find(c=>String(c.url).endsWith('documents:commit')).init.body).writes;assert.equal(writes.length,2);assert.equal(writes[0].currentDocument.updateTime,'v1');h.docs.set('service_requests/order',{fields:{clientUid:{stringValue:'user'},status:{stringValue:'REQUESTED'},photoCount:{integerValue:'6'}}});assert.equal((await h.send('/v1/request-photos',imageForm('REQUEST_PHOTO','order'))).status,409);});
test('foreign identity paths and unauthorized attachments cannot be downloaded',async()=>{const h=setup();assert.equal((await h.send('/v1/document?key=identities/other/x')).status,403);const denied=setup({denied:true});assert.equal((await denied.send('/v1/document?key=request-photos/order/user/id')).status,403);});
